# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db4a2d8f8276d34fc52cc9c7079ff0ad777a8224d1240f09e13a6b497b436715f1c55f64870323cfd99ed93ff6caa2ed67f0a8f2b12aee4832b5f99baa8ef5d

test:
  secret_key_base: 40932adadc4b58883e95ea9773c6970756d64dfee7074f33b70062c77b02ec34e8351880b0bdc9087eb02f6f08267fc3c41d1c38efbb654020f4115773abf403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
